# Site settings
title: "blog.py"
bye_message: "Love responsibility. Say: It is my duty, and mine alone, to save the earth. If it is not saved, then I alone am to blame."
baseurl: "/blog/"
url: "https://odyslam.me"
disqus: odyslam

# Header settings
nick: "hi"
mail:
    domain: "odyslam"
    ext: "me"
source_code:
    server: "github.com"
    nick: "Odyslam"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
